### ISSUE TITLE
Put `lib/` directory into root of vendored package?

### ISSUE THREAD

**Issue by simolus3** [google/dart-neats#183]
I was trying to use the `vendor` tool to vendor `package:tar` into pub's sources. I've used the following configuration:

```yaml
vendored_dependencies:
  tar:
    package: tar
    version: 0.5.5+1
    include:
      - lib/**
      - LICENSE*
      - NOTICE*
```

This is doing what it's supposed to do, but it puts library sources into `src/third_party/tar/lib`. I want them to be directly in `src/third_party/tar/`.

Having them in `lib` causes some problems as the `avoid_relative_lib_imports` lint complains about imports like `import 'third_party/tar/lib/tar.dart'`. This would be a lot easier if the `lib/` folder was just dropped from the path. Since in virtually all (?) cases, the contents of `lib/` is the only thing one would want to vendor, could there be an option to extract contents into a parent folder?

I want this:

 ```
lib/src/third_party/tar/
├── LICENSE
├── tar.dart
└── src/
    ├── constants.dart
    ├── reader.dart
    └── ...
```

Currently, I get this:

```
lib/src/third_party/tar/
├── LICENSE
└── lib/
    ├── tar.dart
    └── src/
        ├── constants.dart
        ├── reader.dart
        └── ...
```

cc @jonasfj
